# Generated by Django 6.0.4 on 2026-04-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
