# Generated by Django 6.0.4 on 2026-04-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_profile_address_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
