# Generated by Django 6.0.4 on 2026-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
