# Generated by Django 6.0.4 on 2026-04-21 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_notification_to_to_user(apps, schema_editor):
    schema_editor.execute(
        'UPDATE "lms_notification" SET "user_id" = "To_id" WHERE "To_id" IS NOT NULL'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_sponsorship_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_notification_to_to_user, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='notification',
            name='From',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='To',
        ),
    ]
