# Generated by Django 6.0.4 on 2026-04-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_notification_sender_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
